import { query } from './database.js';

export async function initializeSchema() {
  await query(`
    CREATE TABLE IF NOT EXISTS reminders (
      id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title                TEXT        NOT NULL,
      description          TEXT,
      time                 TEXT        NOT NULL,
      frequency_type       TEXT        NOT NULL,
      frequency_days       JSONB,
      frequency_interval   INTEGER,
      frequency_start_date TEXT,
      active               BOOLEAN     NOT NULL DEFAULT TRUE,
      created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS email_log (
      id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      reminder_id     INTEGER     NOT NULL REFERENCES reminders(id) ON DELETE CASCADE,
      sent_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
      status          TEXT        NOT NULL,
      error_message   TEXT,
      email_to        TEXT,
      provider_id     TEXT
    );

    CREATE TABLE IF NOT EXISTS reminder_completions (
      id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      reminder_id     INTEGER     NOT NULL REFERENCES reminders(id) ON DELETE CASCADE,
      completed_on    TEXT        NOT NULL,
      completed_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
      UNIQUE(reminder_id, completed_on)
    );

    CREATE TABLE IF NOT EXISTS settings (
      id                         INTEGER PRIMARY KEY CHECK (id = 1),
      email_destination          TEXT        NOT NULL,
      email_enabled              BOOLEAN     NOT NULL DEFAULT TRUE,
      push_notifications_enabled BOOLEAN     NOT NULL DEFAULT FALSE,
      updated_at                 TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    ALTER TABLE email_log ADD COLUMN IF NOT EXISTS email_to TEXT;
    ALTER TABLE email_log ADD COLUMN IF NOT EXISTS provider_id TEXT;
  `);

  await query(`
    INSERT INTO settings (id, email_destination, email_enabled, push_notifications_enabled)
    VALUES (1, $1, TRUE, FALSE)
    ON CONFLICT(id) DO NOTHING
  `, [process.env.USER_EMAIL ?? '']);
}
